name: Deploy

on:
  push:
    branches:
      - main
      
  workflow_dispatch:
    
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          yarn build
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=${{ vars.CF_PAGES_NAME }}
      - name: Purge CloudFlare Cache
        if: vars.PURGE_CF_CACHE == '1'
        run: |
          curl --request POST \
            --url https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Bearer ${{ secrets.CF_TOKEN }}' \
            --data '{
              "files": [
                "${{ secrets.CF_CODEX_URL }}"
              ]
            }'
